# Installing and docker 
yum install docker -y
docker --version 

# start docker services
service docker start
service docker status

#Installing docker compsoe , on Ubuntu 
sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version

#creating the docker compose file  for Kafka and Redis 

version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
	
	volumes:
     - $PWD/Kafka-data:/tmp/kafka-logs
	

  redis:
    image: "redis:alpine"
	container_name: redis

    ports:
     - "6379:6379"

    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master
	  
	  
